### ISSUE TITLE
[ASSIGNMENT 2][Task 3.2] Add data output to written file

### ISSUE THREAD

**Issue by real-darth** [real-darth/Group-2---High-Performance-Computing#9]
For quality of life, it would be nice if the data collected in Task 3.2 could be saved in a file instead of just printed in the logs / plotted in a graph.

I will try to look into this myself, but if anyone have any tips on how this could be nicley implemented, I am open to suggestions!

**Comment by arejula27** [comment]
I have done it in the extra bonus, take a look into the time_measurer file, line 120, i use it in the plot.py file
